Algoritmo "Creuza3"

Var
   N,C:real


Inicio
      Escreval("No Brasil a temperatura é medida por graus Celsius ")
      Escreval("Aqui, é medido em Fahrenheit. Preciso converter")
      Escreval("Lembro, que a fórmula é de C=F-32/1.8")
      Escreval("Então, quantos Fahrenheits está fazendo aqui em New York? ")
      Leia (N)
      Escreval("Então, está ", N, " Fahrenheits ")
      C<-((N-32)/1.8))
      Escreva("Então, se eu estivesse no Brasil, seria de ", Int(C), " graus ")



Fimalgoritmo