Algoritmo "EstruturaCondicional3"

Var
   N,N1:inteiro


Inicio
      Escreva("Início:")
      Leia(N)
      Escreva("Fim:" )
      Leia(N1)
      Se(N<N1)entao
         para N<-N ate N1 passo 1 faca
           Escreva(N)
         FimPara
      senao
         Se(N>N1)entao
            para N<-N ate N1 passo (-1)faca
              Escreva(N)
            Fimpara
         FimSe
      FimSe


Fimalgoritmo